### ISSUE TITLE
When column length is too less restore to default value.

### ISSUE THREAD

**Issue by shivanshu-semwal** [glennular/i3help#3]
I tried this `i3help -l 10`, and got the warning(or error I guess), 
```
(i3help:32016): GLib-CRITICAL **: 15:29:34.967: g_strjoinv: assertion 'str_array != NULL' failed
```
I think restoring to default value of parameter and then giving a warning for invalid value would be a fix?
Thanks!

**Comment by glennular** [comment]
@shivanshu-semwal added some error checking to ensure there are no errors thrown when the length is shorter than the key bindings.

Having such a small length (like 10) will result in weird outputs but i didn't want to limit the length since someone might have a need.

change: ef649d4
