### ISSUE TITLE
Instructions on how to change look

### ISSUE THREAD

**Issue by Amulek1416** [glennular/i3help#4]
The gif shown in `README.md` has i3help with a dark background while i3help is white by default. Could there be more instructions on how to change the look of the window? Or maybe a way to support themes?  

Thanks for the work that has been put into this. I feel that this is something that should be native in i3 and is a great idea.

**Comment by glennular** [comment]
i3help is built upon GTK. It uses the system's set theme by default, and if you would like you can manually set the theme at runtime.  A good place to find more about themes for GTK is on the Arch Wiki: https://wiki.archlinux.org/title/GTK

In the screenshot you will see the [Arc-Dark](https://github.com/jnsh/arc-theme) theme.

**Comment by Amulek1416** [comment]
> i3help is built upon GTK. It uses the system's set theme by default, and if you would like you can manually set the theme at runtime. A good place to find more about themes for GTK is on the Arch Wiki: https://wiki.archlinux.org/title/GTK
> 
> In the screenshot you will see the [Arc-Dark](https://github.com/jnsh/arc-theme) theme.

Thanks! It may be beneficial to put a line about this in the README
